apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: insights-client-certs 
  labels:
    app: {{ template "insights.name" . }}
    chart: {{ template "insights.chart" . }}
    release: {{ .Release.Name }}
    component: "insights"
    heritage: {{ .Release.Service }}
spec:
  secretName: insights-client-certs 
  issuerRef:
    name: {{ .Values.global.certificateAuthority.issuer }}
    kind: {{ .Values.global.certificateAuthority.kind }}
  commonName: insights-client 
  dnsNames:
  - insights-insights-client 
  - insights-insights-client.{{ .Release.Namespace }}
  - insights-insights-client.{{ .Release.Namespace }}.svc
  organization:
  - Red Hat
