# Copyright (c) 2020 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
kind: ServiceAccount
metadata:
  name: insights-client
  labels:
    app: {{ .Values.insights.name }}
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    component: insights-client
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
